swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts and Transactions Module
      summary: All user's accounts
      description: API for get all user's accounts
      responses:
        '200':
          description: All user's accounts retrieved successully
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: No accounts found
        '500':
          description: Internal Server Error

  /user/accounts/{accountID}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts and Transactions Module
      summary: Account transactions
      description: API for retrieving list of transactions assiocated with an account
      parameters:
        - in: path
          name: accountID
          description: ID of an account
          required: true
          type: string
      responses:
        '200':
          description: All transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'

        '400':
          description: Account not found
        '401':
          description: No transaction found
        '403':
          description: Unauthorized user, token is missing
        '500':
          description: Internal Server Error

  /user/accounts/transactions/{transactionID}/category:
    put:
      tags:
        - Accounts and Transactions Module
      summary: Update transaction's category
      description: API for updating category of transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: body
          name: category
          description: Modified transaction's category
          required: true
          schema:
            $ref: '#/definitions/TransactionCategory'
      responses:
        '200':
          description: Transaction's category modified successfully
          schema:
            $ref: '#/definitions/TransactionCategory'
        '401':
          description: Transaction not found
        '403':
          description: Unauthorized user, token is missing
        '500':
          description: Internal Server Error

  /user/accounts/transactions/{transactionID}/note:
    post:
      tags:
        - Accounts and Transactions Module
      summary: Update transaction's note
      description: API for adding a note to a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: body
          name: note
          description: New transaction's note
          required: true
          schema:
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note succesfully added to transaction
          schema:
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Note could not be added
        '403':
          description: Unauthorized user, token is missing
        '500':
          description: Internal Server Error

  /user/accounts/transactions/{transactionID}/note/{noteID}:
    put:
      tags:
        - Accounts and Transactions Module
      summary: Edit transaction's note
      description: API for editing a note of a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: path
          name: noteID
          description: ID of a note
          required: true
          type: string
        - in: body
          name: note
          description: Edit transaction's note
          required: true
          schema:
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note edited successfully
          schema:
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Note could not be edited
        '403':
          description: Unauthorized user, token is missing
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Accounts and Transactions Module
      summary: Delete transaction's note
      description: API for deleting a note of a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: path
          name: noteID
          description: ID of a note
          required: true
          type: string
      responses:
        '200':
          description: Note deleted successfully
        '401':
          description: Note not deleted
        '403':
          description: Unauthorized user, token is missing
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  AccountsResponse:
    type: object
    properties:
      transactions:
        type: string
  TransactionsResponse:
    type: object
    properties:
      transactionID:
        type: string
        description: transaction ID
      transactionType:
        type: string
        description: type of transaction
      date:
        type: string
        format: date-time
        description: date of transaction
      description:
        type: string
        description: description of transaction
      amount:
        type: number
        description: transaction amout
      balance:
        type: number
        description: available balance
        format: double
      category:
        type: string
        description: name of the category
      note:
        type: string
        description: user note
  TransactionCategory:
    type: object
    properties:
      category:
        type: string
  TransactionNote:
    type: object
    properties:
      note:
        type: string
  TransactionResponseNote:
    type: object
    properties:
      note:
        type: string
      noteID:
        type: string
